# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 835e853e3e0e22f08b266a3f759589d54d1d2bb9d41b5d2cd23c5dcfe18c1dac4a8a7125613cfaefbac43fa74e72591420c21dc7aac5a359b8a531f8c814e4f3

test:
  secret_key_base: b8d1887a8e5aae86c38c7052aea73d945890c8f4a5b3668112498ea4b93cbd8d426747ba7fe24b2cbb68f6dfaf04dc141238effbe3ef9a48a6b652a8911562a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
